
create or replace function tenants.create_tenant(schema_name text) returns void as $$
begin
    -- 1. crear el esquema
    execute format('create schema if not exists %I', schema_name);

    -- 2. cambiar el path
    execute format('set local search_path to %I', schema_name);

    -- 3. tablas
    create table if not exists ubications (
        id bigint generated by default as identity primary key,
        name varchar(255) not null,
        address text,
        created_at timestamp with time zone default current_timestamp,
        updated_at timestamp with time zone default current_timestamp
    );

    create table if not exists stores (
        id bigint generated by default as identity primary key,
        ubication_id bigint not null,
        name varchar(255) not null,
        status varchar(50) default 'active',
        created_at timestamp with time zone default current_timestamp,
        updated_at timestamp with time zone default current_timestamp,
    
        constraint fk_stores_ubication 
            foreign key (ubication_id) 
            references ubications(id) 
            on delete restrict
    );

    create index if not exists idx_stores_ubication_id on stores(ubication_id);

    create table if not exists users (
        id serial primary key, 
        username varchar(100) not null, 
        password varchar(100) not null,
        created_at timestamp with time zone default current_timestamp,
        updated_at timestamp with time zone default current_timestamp,
        last_active_at timestamp with time zone,
        deleted_at timestamp with time zone
    );

    create table if not exists user_stores (
        user_id int not null,
        store_id bigint not null,
        primary key (user_id, store_id),
        
        constraint fk_user_stores_user 
            foreign key (user_id) 
            references users(id) 
            on delete cascade,
            
        constraint fk_user_stores_store 
            foreign key (store_id) 
            references stores(id) 
            on delete cascade
    );

    create table if not exists roles (
        id serial primary key,
        name varchar(50) unique not null 
    );

    create table if not exists user_roles (
        user_id int not null,
        role_id int not null,
        primary key (user_id, role_id),
        constraint fk_user foreign key (user_id) references users(id) on delete cascade,
        constraint fk_role foreign key (role_id) references roles(id) on delete cascade
    );

    create table if not exists permissions (
        id serial primary key,
        name varchar(100) unique not null
    );

    create table if not exists role_permissions (
        role_id int not null,
        permission_id int not null,
        primary key (role_id, permission_id),
        constraint fk_role_perm foreign key (role_id) references roles(id) on delete cascade,
        constraint fk_permission_role foreign key (permission_id) references permissions(id) on delete cascade
    );

    create table if not exists products (
        id serial primary key,
        name varchar(150) not null,
        description text,
        price decimal(12, 2) not null default 0.00,
        stock int not null default 0,
        user_id int not null, 
        created_at timestamp with time zone default current_timestamp,
        updated_at timestamp with time zone default current_timestamp,
        deleted_at timestamp with time zone,
        constraint fk_products_user foreign key (user_id) references users(id) on delete cascade
    );

    create table if not exists sales (
        id serial primary key,
        user_id int not null, 
        total_amount decimal(12, 2) not null default 0.00,
        status varchar(20) default 'pending', 
        created_at timestamp with time zone default current_timestamp,
        updated_at timestamp with time zone default current_timestamp,
        deleted_at timestamp with time zone,
        constraint fk_sales_user foreign key (user_id) references users(id)
    );

    -- 4. inserts iniciales
    insert into roles (name) values ('admin'), ('user')
    on conflict (name) do nothing;

    insert into permissions (name) values ('read'), ('write'), ('delete')
    on conflict (name) do nothing;

    insert into role_permissions (role_id, permission_id)
    select r.id, p.id 
    from roles r, permissions p
    where r.name = 'admin'
    on conflict do nothing;

end; $$ language plpgsql;
