spring.application.name=punto-venta
server.port=${SPRING_PORT:8081}

#DatatSource Hikari
spring.datasource.url=jdbc:postgresql://localhost:5432/nns-one
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.yml

#Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=com.nns.punto_venta.controllers
#springdoc.pathsToMatch=/v1, /api/balance/**
server.forward-headers-strategy=native
